import=["~/.cache/wal/alacritty.toml"]
[font]
size = 12

[font.normal]
family ="CaskaydiaCove NFM" # 33 130
# family ="Hack" # 33 130
# family ="Operator Mono" # 32 140
# family ="Sarasa Term SC" # 30 153
style = "Medium"

[font.bold]
# family ="Sarasa Term SC" # 30 153
# family ="Operator Mono" # 32 140
family ="CaskaydiaCove NFM" # 33 130
# family ="Hack" # 33 130
style = "Bold"

[font.italic]
# family ="CaskaydiaCove NFM"
# family ="Hack"
family ="Operator Mono"
# family ="Sarasa Term SC"
style = "Medium Italic"

[font.bold_italic]
# family ="CaskaydiaCove NFM"
# family ="Hack"
family ="Operator Mono"
# family ="Sarasa Term SC"
style = "Bold Italic"

[shell]
program = "/bin/zsh"

[window.dimensions]
columns = 80
lines = 24

[window]
opacity = 0.9
