#!/usr/bin/env bash
sleep 3 && parallel ::: '/usr/lib/kdeconnectd' kdeconnect-indicator localsend syncthing keepassxc 'cd ~/Yacd-meta && pnpm start' 'aria2c --enable-rpc' 'foot --server' 'colormgr get-devices'
