#!/usr/bin/zsh

export BEMENU_OPTS='--fb "#eff1f5" --ff "#4c4f69" --nb "#eff1f5" --nf "#4c4f69" --tb "#eff1f5" --hb "#eff1f5" --tf "#d20f39" --hf "#df8e1d" --nf "#4c4f69" --af "#4c4f69" --ab "#eff1f5"'
bemenu-run -H 31
