[colors]
ansi = [
    '',
    '#100F0F',
    '#AF3029',
    '#66800B',
    '#AD8301',
    '#205EA6',
    '#A02F6F',
    '#24837B',
]
background = '#100F0F'
brights = [
    '#F2F0E5',
    '#6F6E69',
    '#D14D41',
    '#879A39',
    '#D0A215',
    '#4385BE',
    '#CE5D97',
    '#3AA99F',
]
cursor_bg = '#CECDC3'
cursor_border = '#CECDC3'
cursor_fg = '#CECDC3'
foreground = '#CECDC3'
selection_bg = '#CECDC3'
selection_fg = '#CECDC3'

[colors.indexed]

[metadata]
author = 'hydroakri'
name = '"flexoki-dark"'
