#!/bin/sh
# Darkman theme switcher. Receives the current mode ("dark" or "light") as $1.
mode="$1"

if [ "$mode" = "dark" ]; then
    gtk_theme="adw-gtk3-dark"
    icon_theme="Papirus-Dark"
    qt_style="Adwaita-dark"
    qt_scheme="~/.config/qt6ct/colors/flexoki-dark.conf"
else
    gtk_theme="adw-gtk3"
    icon_theme="Papirus"
    qt_style="Adwaita"
    qt_scheme="~/.config/qt6ct/colors/flexoki-light.conf"
fi

# Tell noctalia to switch its dark/light variant: it regenerates gtk.css
# and syncs gsettings itself. Skip silently if noctalia isn't running.
if [ "$mode" = "dark" ]; then
    noctalia-shell ipc call darkMode setDark 2>/dev/null || true
else
    noctalia-shell ipc call darkMode setLight 2>/dev/null || true
fi

gsettings set org.gnome.desktop.interface color-scheme "prefer-$mode"
gsettings set org.gnome.desktop.interface gtk-theme "$gtk_theme"
gsettings set org.gnome.desktop.interface icon-theme "$icon_theme"

# gtk.css is now generated by noctalia; do not overwrite it.
# qt5ct shares qt6ct's config file so darkman only edits one copy.
mkdir -p ~/.config/qt5ct
ln -sf ~/.config/qt6ct/qt6ct.conf ~/.config/qt5ct/qt5ct.conf
sed -i "/^style=/c style=$qt_style" ~/.config/qt6ct/qt6ct.conf
grep -q "^style=" ~/.config/qt6ct/qt6ct.conf || echo "style=$qt_style" >>~/.config/qt6ct/qt6ct.conf
sed -i "/^icon_theme=/c icon_theme=$icon_theme" ~/.config/qt6ct/qt6ct.conf
grep -q "^icon_theme=" ~/.config/qt6ct/qt6ct.conf || echo "icon_theme=$icon_theme" >>~/.config/qt6ct/qt6ct.conf
sed -i "/^color_scheme_path=/c color_scheme_path=$qt_scheme" ~/.config/qt6ct/qt6ct.conf
grep -q "^color_scheme_path=" ~/.config/qt6ct/qt6ct.conf || echo "color_scheme_path=$qt_scheme" >>~/.config/qt6ct/qt6ct.conf
