[Autologin]
Relogin=false
Session=
User=

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Theme]
Current=Dracula
CursorTheme=Dracula-cursors
Font=更纱黑体 SC,14,-1,5,63,0,0,0,0,0,Semibold

[Users]
MaximumUid=60513
MinimumUid=1000
