#--enable-features=WaylandWindowDecorations
#--enable-webrtc-pipewire-capture
# --gtk-version=4
#
#--force-device-scale-factor=1.46875
--ozone-platform-hint=auto
--enable-wayland-ime
--enable-features=UseOzonePlatform
