[General]
configuration_screencast_save_folder=/home/hydroakri
credentials.password=@ByteArray(\x1f._\x15^\vFRIE\x1fI)
customer.email=hsx011231@gmail.com
eula-id.agreed=-1
height=768
host.only.interface=vboxnet0
proxy.enabled=true
proxy.host=127.0.0.1
proxy.port=7890
stats.installation.date=1653111452
stats.last=1653398707
vms.path=/home/hydroakri/.Genymobile/Genymotion/deployed/
whats.new.popup.last.version=3.2.1
width=1024
x=430
y=130
