[Settings]
Compiler\CCompiler=
Compiler\CXXCompiler=
Compiler\FortranCompiler=
CrossCompiler\CCompiler=
CrossCompiler\CXXCompiler=
CrossCompiler\FindRoot=
CrossCompiler\FortranCompiler=
CrossCompiler\IncludeMode=0
CrossCompiler\LibraryMode=0
CrossCompiler\ProgramMode=0
CrossCompiler\SystemName=
CrossCompiler\SystemProcessor=
CrossCompiler\SystemVersion=
CrossCompiler\ToolChainFile=
StartPath\AdvancedView=true
StartPath\GroupView=false
StartPath\LastGenerator=Unix Makefiles
StartPath\SplitterSizes=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\x3\xc6\0\0\0\xc0\x1\xff\xff\xff\xff\x1\0\0\0\x2\0)
StartPath\WhereBuild0=/home/hydroakri/opencv/build
StartPath\geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\xef\0\0\x4\xa7\0\0\x6\xed\0\0\a\xec\0\0\0\xef\0\0\x4\xc5\0\0\x6\xed\0\0\a\xec\0\0\0\x1\0\0\0\0\a\x80\0\0\0\xef\0\0\x4\xc5\0\0\x6\xed\0\0\a\xec)
StartPath\windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x5\xff\0\0\x3\r\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)
