# XXX DO NOT FORGET TO BACKUP /etc/ssh before fresh install!!
# XXX: 强状态依赖 - SSH主机密钥必须存在才能解密sops密钥
#
# For common key: DO `cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age`
# For hardware security: DO `age-plugin-fido2-hmac -g > ./age-identity-pico.txt` then place the public key aged below
#
# After add new public key run `sops updatekeys secrets.yaml`
keys:
  - &hydroakri age13dfnenxe5k0wlyj5xt9xljul9gljylzg2wz06hlslz6xyk296qqs26twx0
  - &omen15 age1sndl2ewalys8v7mk78fps8qkjq8azs49ymy25gnyamjv2f0qafsqdztsd8
  - &rpi4 age1rdsf9knqawl06a8tgzhn24g5ueeggxzge0ejz6h362pnfp55v93qeackm3
  - &hydroakri-sk age1572ugfjxd8qwl4ze96hcq7lu3h9hxrlay9hpju4038t0sven0shslhfv65

creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *hydroakri
          - *omen15
          - *rpi4
