#!/bin/sh
export LIBVA_DRIVER_NAME=nvidia # need commented to start obs-studio and chromium
export XDG_SESSION_TYPE=wayland
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export __GL_SYNC_TO_VBLANK=1

export QT_QPA_PLATFORM=wayland
export GDK_BACKEND=wayland
export SDL_VIDEODRIVER=wayland
export CLUTTER_BACKEND=wayland
export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway

export XCURSOR_SIZE=24
export QT_QPA_PLATFORMTHEME=qt5ct

export GTK_IM_MODULE=wayland
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export SDL_IM_MODULE=fcitx
export GLFW_IM_MODULE=ibus

export EDITOR=nvim
export VISUAL=nvim

exec sway --unsupported-gpu "$@"
