# This is the configuration file for animwall
#
# Entries are expected one per line in the format
# <FILE>:<WIDTHxHEIGHT+X+Y>:<SCREEN>
#
# Lines beginning with # are ignored
~/wallpapers/example_1.mp4:1920x1080+0+0:0
~/pictures/example2.jpg:2560x1440+1920+0:1
