# Use custom format:
# format="$username@$hostname $directory$character$git_branch"
palette = 'flexoki'

# [character]
#
# [directory]
# style = 'bold grey'
#
# [git_branch]
#
# [hostname]
# ssh_only = false
# format = '[$ssh_symbol](bold blue)[$hostname](bold grey)'
# disabled = false
#
# [username]
# format = '[$user](bold green)'
# disabled = false
# show_always = true



[character]
vimcmd_symbol = '[](bold green)'

[shell]
fish_indicator = ''
zsh_indicator = '%'
bash_indicator = '󱆃'
powershell_indicator = ''
style = 'cyan bold'
disabled = false

[palettes.flexoki]
black = "#100F0F"
red = "#D14D41"
green = "#879A39"
yellow = "#D0A215"
blue = "#4385BE"
magenta = "#CE5D97"
cyan = "#3AA99F"
white = "#CECDC3"
bright-black = "#100F0F"
bright-red = "#AF3029"
bright-green = "#66800B"
bright-yellow = "#AD8301"
bright-blue = "#205EA6"
bright-magenta = "#A02F6F"
bright-cyan = "#24837B"
bright-white = "#FFFCF0"

