name: "nix flake update"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  flake-check:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Determinate Nix
        uses: DeterminateSystems/determinate-nix-action@v3
      - name: Flake sanity check
        run: |
          nix flake show ./flake >/dev/null

  update-flake-lock:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Determinate Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Check if Kernel (Xanmod) needs update
        id: check_kernel
        run: |
          cd flake
          CURRENT_HASH=$(nix eval .#nixosConfigurations.omen15.config.boot.kernelPackages.kernel.outPath --raw)
          REMOTE_HASH=$(nix eval github:NixOS/nixpkgs/nixos-unstable#linuxPackages_xanmod.kernel.outPath --raw)
          echo "当前系统锁定的内核版本哈希: $CURRENT_HASH"
          echo "上游云端最新的内核版本哈希: $REMOTE_HASH"
          if [ "$CURRENT_HASH" != "$REMOTE_HASH" ]; then
            echo "检测到内核变动，准备执行 flake update。"
            echo "should_update=true" >> "$GITHUB_OUTPUT"
          else
            echo "内核哈希一致，跳过本次更新。"
            echo "should_update=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Update flake.lock
        if: steps.check_kernel.outputs.should_update == 'true'
        id: update_step
        uses: DeterminateSystems/update-flake-lock@main
        with:
          path-to-flake-dir: flake
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          pr-title: "chore(deps): nix flake update"
          pr-labels: |
            automated
            dependencies

      - name: Approve and Enable Auto-merge
        if: steps.check_kernel.outputs.should_update == 'true' && steps.update_step.outputs.pull-request-number != ''
        run: |
          PR_NUM=${{ steps.update_step.outputs.pull-request-number }}
          gh pr merge "$PR_NUM" --auto --squash
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
